kind: pipeline
name: default

steps:
  - name: test
    image: node
    commands:
      - apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - npm install
      - npm test
