kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: node
    commands:
      - npm install
      - npm test
  - name: publish
    image: appleboy/drone-scp
    settings:
      host: 192.168.0.197
      user: arthas
      key:
        from_secret: ssh_key
      target: /home/arthas/staging/michael-rosenbot
      source: "*"
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host: 192.168.0.197
      user: arthas
      key:
        from_secret: ssh_key
      script:
      - pwd
      - cp ~/secrets.json ~/staging/michael-rosenbot

