kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: node
    commands:
      - npm install
      - npm test

  - name: deploy
    image: appleboy/drone-scp
    settings:
      host: 192.168.0.197
      user: arthas
      key:
        from_secret: ssh_key
      target: /home/arthas/staging/michael-rosenbot
      source: "*"

  - name: run
    image: appleboy/drone-ssh
    settings:
      host: 192.168.0.197
      user: arthas
      key:
        from_secret: ssh_key
      script:
      - cp ~/secrets.json ~/staging/michael-rosenbot
      - cd ~/staging/michael-rosenbot
      - docker build -t michael-rosenbot .
      - docker stop michael-rosenbot
      - docker container rm michael-rosenbot
      - docker run -d --name michael-rosenbot --mount source=mr-data,destination=/usr/src/michael-rosenbot/data michael-rosenbot

